/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppAccountRouteImport } from './routes/_app.account'
import { Route as AppCataloghiRouteImport } from './routes/_app.cataloghi'
import { Route as AppCategorieRouteImport } from './routes/_app.categorie'
import { Route as AppCercaRouteImport } from './routes/_app.cerca'
import { Route as AppChiSiamoRouteImport } from './routes/_app.chi-siamo'
import { Route as AppConfrontaRouteImport } from './routes/_app.confronta'
import { Route as AppConsegneRouteImport } from './routes/_app.consegne'
import { Route as AppContattiRouteImport } from './routes/_app.contatti'
import { Route as AppDoveSiamoRouteImport } from './routes/_app.dove-siamo'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppIMieiOrdiniRouteImport } from './routes/_app.i-miei-ordini'
import { Route as AppNovitaRouteImport } from './routes/_app.novita'
import { Route as AppOfferteRouteImport } from './routes/_app.offerte'
import { Route as AppPiuVendutiRouteImport } from './routes/_app.piu-venduti'
import { Route as AppPreferitiRouteImport } from './routes/_app.preferiti'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCategorieRouteImport } from './routes/admin.categorie'
import { Route as AdminClientiRouteImport } from './routes/admin.clienti'
import { Route as AdminImpostazioniRouteImport } from './routes/admin.impostazioni'
import { Route as AdminOrdiniRouteImport } from './routes/admin.ordini'
import { Route as AdminProdottiRouteImport } from './routes/admin.prodotti'
import { Route as AdminSottocategorieRouteImport } from './routes/admin.sottocategorie'
import { Route as AdminUtentiRouteImport } from './routes/admin.utenti'
import { Route as AppCategorieSlugRouteImport } from './routes/_app.categorie.$slug'
import { Route as AppProdottoIdRouteImport } from './routes/_app.prodotto.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppCataloghiRoute = AppCataloghiRouteImport.update({
  id: '/cataloghi',
  path: '/cataloghi',
  getParentRoute: () => AppRoute,
} as any)
const AppCategorieRoute = AppCategorieRouteImport.update({
  id: '/categorie',
  path: '/categorie',
  getParentRoute: () => AppRoute,
} as any)
const AppCercaRoute = AppCercaRouteImport.update({
  id: '/cerca',
  path: '/cerca',
  getParentRoute: () => AppRoute,
} as any)
const AppChiSiamoRoute = AppChiSiamoRouteImport.update({
  id: '/chi-siamo',
  path: '/chi-siamo',
  getParentRoute: () => AppRoute,
} as any)
const AppConfrontaRoute = AppConfrontaRouteImport.update({
  id: '/confronta',
  path: '/confronta',
  getParentRoute: () => AppRoute,
} as any)
const AppConsegneRoute = AppConsegneRouteImport.update({
  id: '/consegne',
  path: '/consegne',
  getParentRoute: () => AppRoute,
} as any)
const AppContattiRoute = AppContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => AppRoute,
} as any)
const AppDoveSiamoRoute = AppDoveSiamoRouteImport.update({
  id: '/dove-siamo',
  path: '/dove-siamo',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppIMieiOrdiniRoute = AppIMieiOrdiniRouteImport.update({
  id: '/i-miei-ordini',
  path: '/i-miei-ordini',
  getParentRoute: () => AppRoute,
} as any)
const AppNovitaRoute = AppNovitaRouteImport.update({
  id: '/novita',
  path: '/novita',
  getParentRoute: () => AppRoute,
} as any)
const AppOfferteRoute = AppOfferteRouteImport.update({
  id: '/offerte',
  path: '/offerte',
  getParentRoute: () => AppRoute,
} as any)
const AppPiuVendutiRoute = AppPiuVendutiRouteImport.update({
  id: '/piu-venduti',
  path: '/piu-venduti',
  getParentRoute: () => AppRoute,
} as any)
const AppPreferitiRoute = AppPreferitiRouteImport.update({
  id: '/preferiti',
  path: '/preferiti',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategorieRoute = AdminCategorieRouteImport.update({
  id: '/categorie',
  path: '/categorie',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientiRoute = AdminClientiRouteImport.update({
  id: '/clienti',
  path: '/clienti',
  getParentRoute: () => AdminRoute,
} as any)
const AdminImpostazioniRoute = AdminImpostazioniRouteImport.update({
  id: '/impostazioni',
  path: '/impostazioni',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdiniRoute = AdminOrdiniRouteImport.update({
  id: '/ordini',
  path: '/ordini',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdottiRoute = AdminProdottiRouteImport.update({
  id: '/prodotti',
  path: '/prodotti',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSottocategorieRoute = AdminSottocategorieRouteImport.update({
  id: '/sottocategorie',
  path: '/sottocategorie',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUtentiRoute = AdminUtentiRouteImport.update({
  id: '/utenti',
  path: '/utenti',
  getParentRoute: () => AdminRoute,
} as any)
const AppCategorieSlugRoute = AppCategorieSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppCategorieRoute,
} as any)
const AppProdottoIdRoute = AppProdottoIdRouteImport.update({
  id: '/prodotto/$id',
  path: '/prodotto/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/account': typeof AppAccountRoute
  '/cataloghi': typeof AppCataloghiRoute
  '/categorie': typeof AppCategorieRouteWithChildren
  '/cerca': typeof AppCercaRoute
  '/chi-siamo': typeof AppChiSiamoRoute
  '/confronta': typeof AppConfrontaRoute
  '/consegne': typeof AppConsegneRoute
  '/contatti': typeof AppContattiRoute
  '/dove-siamo': typeof AppDoveSiamoRoute
  '/home': typeof AppHomeRoute
  '/i-miei-ordini': typeof AppIMieiOrdiniRoute
  '/novita': typeof AppNovitaRoute
  '/offerte': typeof AppOfferteRoute
  '/piu-venduti': typeof AppPiuVendutiRoute
  '/preferiti': typeof AppPreferitiRoute
  '/admin/categorie': typeof AdminCategorieRoute
  '/admin/clienti': typeof AdminClientiRoute
  '/admin/impostazioni': typeof AdminImpostazioniRoute
  '/admin/ordini': typeof AdminOrdiniRoute
  '/admin/prodotti': typeof AdminProdottiRoute
  '/admin/sottocategorie': typeof AdminSottocategorieRoute
  '/admin/utenti': typeof AdminUtentiRoute
  '/admin/': typeof AdminIndexRoute
  '/categorie/$slug': typeof AppCategorieSlugRoute
  '/prodotto/$id': typeof AppProdottoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account': typeof AppAccountRoute
  '/cataloghi': typeof AppCataloghiRoute
  '/categorie': typeof AppCategorieRouteWithChildren
  '/cerca': typeof AppCercaRoute
  '/chi-siamo': typeof AppChiSiamoRoute
  '/confronta': typeof AppConfrontaRoute
  '/consegne': typeof AppConsegneRoute
  '/contatti': typeof AppContattiRoute
  '/dove-siamo': typeof AppDoveSiamoRoute
  '/home': typeof AppHomeRoute
  '/i-miei-ordini': typeof AppIMieiOrdiniRoute
  '/novita': typeof AppNovitaRoute
  '/offerte': typeof AppOfferteRoute
  '/piu-venduti': typeof AppPiuVendutiRoute
  '/preferiti': typeof AppPreferitiRoute
  '/admin/categorie': typeof AdminCategorieRoute
  '/admin/clienti': typeof AdminClientiRoute
  '/admin/impostazioni': typeof AdminImpostazioniRoute
  '/admin/ordini': typeof AdminOrdiniRoute
  '/admin/prodotti': typeof AdminProdottiRoute
  '/admin/sottocategorie': typeof AdminSottocategorieRoute
  '/admin/utenti': typeof AdminUtentiRoute
  '/admin': typeof AdminIndexRoute
  '/categorie/$slug': typeof AppCategorieSlugRoute
  '/prodotto/$id': typeof AppProdottoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/cataloghi': typeof AppCataloghiRoute
  '/_app/categorie': typeof AppCategorieRouteWithChildren
  '/_app/cerca': typeof AppCercaRoute
  '/_app/chi-siamo': typeof AppChiSiamoRoute
  '/_app/confronta': typeof AppConfrontaRoute
  '/_app/consegne': typeof AppConsegneRoute
  '/_app/contatti': typeof AppContattiRoute
  '/_app/dove-siamo': typeof AppDoveSiamoRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/i-miei-ordini': typeof AppIMieiOrdiniRoute
  '/_app/novita': typeof AppNovitaRoute
  '/_app/offerte': typeof AppOfferteRoute
  '/_app/piu-venduti': typeof AppPiuVendutiRoute
  '/_app/preferiti': typeof AppPreferitiRoute
  '/admin/categorie': typeof AdminCategorieRoute
  '/admin/clienti': typeof AdminClientiRoute
  '/admin/impostazioni': typeof AdminImpostazioniRoute
  '/admin/ordini': typeof AdminOrdiniRoute
  '/admin/prodotti': typeof AdminProdottiRoute
  '/admin/sottocategorie': typeof AdminSottocategorieRoute
  '/admin/utenti': typeof AdminUtentiRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/categorie/$slug': typeof AppCategorieSlugRoute
  '/_app/prodotto/$id': typeof AppProdottoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/account'
    | '/cataloghi'
    | '/categorie'
    | '/cerca'
    | '/chi-siamo'
    | '/confronta'
    | '/consegne'
    | '/contatti'
    | '/dove-siamo'
    | '/home'
    | '/i-miei-ordini'
    | '/novita'
    | '/offerte'
    | '/piu-venduti'
    | '/preferiti'
    | '/admin/categorie'
    | '/admin/clienti'
    | '/admin/impostazioni'
    | '/admin/ordini'
    | '/admin/prodotti'
    | '/admin/sottocategorie'
    | '/admin/utenti'
    | '/admin/'
    | '/categorie/$slug'
    | '/prodotto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/account'
    | '/cataloghi'
    | '/categorie'
    | '/cerca'
    | '/chi-siamo'
    | '/confronta'
    | '/consegne'
    | '/contatti'
    | '/dove-siamo'
    | '/home'
    | '/i-miei-ordini'
    | '/novita'
    | '/offerte'
    | '/piu-venduti'
    | '/preferiti'
    | '/admin/categorie'
    | '/admin/clienti'
    | '/admin/impostazioni'
    | '/admin/ordini'
    | '/admin/prodotti'
    | '/admin/sottocategorie'
    | '/admin/utenti'
    | '/admin'
    | '/categorie/$slug'
    | '/prodotto/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/auth'
    | '/_app/account'
    | '/_app/cataloghi'
    | '/_app/categorie'
    | '/_app/cerca'
    | '/_app/chi-siamo'
    | '/_app/confronta'
    | '/_app/consegne'
    | '/_app/contatti'
    | '/_app/dove-siamo'
    | '/_app/home'
    | '/_app/i-miei-ordini'
    | '/_app/novita'
    | '/_app/offerte'
    | '/_app/piu-venduti'
    | '/_app/preferiti'
    | '/admin/categorie'
    | '/admin/clienti'
    | '/admin/impostazioni'
    | '/admin/ordini'
    | '/admin/prodotti'
    | '/admin/sottocategorie'
    | '/admin/utenti'
    | '/admin/'
    | '/_app/categorie/$slug'
    | '/_app/prodotto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cataloghi': {
      id: '/_app/cataloghi'
      path: '/cataloghi'
      fullPath: '/cataloghi'
      preLoaderRoute: typeof AppCataloghiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categorie': {
      id: '/_app/categorie'
      path: '/categorie'
      fullPath: '/categorie'
      preLoaderRoute: typeof AppCategorieRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cerca': {
      id: '/_app/cerca'
      path: '/cerca'
      fullPath: '/cerca'
      preLoaderRoute: typeof AppCercaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chi-siamo': {
      id: '/_app/chi-siamo'
      path: '/chi-siamo'
      fullPath: '/chi-siamo'
      preLoaderRoute: typeof AppChiSiamoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/confronta': {
      id: '/_app/confronta'
      path: '/confronta'
      fullPath: '/confronta'
      preLoaderRoute: typeof AppConfrontaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/consegne': {
      id: '/_app/consegne'
      path: '/consegne'
      fullPath: '/consegne'
      preLoaderRoute: typeof AppConsegneRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contatti': {
      id: '/_app/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof AppContattiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dove-siamo': {
      id: '/_app/dove-siamo'
      path: '/dove-siamo'
      fullPath: '/dove-siamo'
      preLoaderRoute: typeof AppDoveSiamoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/i-miei-ordini': {
      id: '/_app/i-miei-ordini'
      path: '/i-miei-ordini'
      fullPath: '/i-miei-ordini'
      preLoaderRoute: typeof AppIMieiOrdiniRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/novita': {
      id: '/_app/novita'
      path: '/novita'
      fullPath: '/novita'
      preLoaderRoute: typeof AppNovitaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offerte': {
      id: '/_app/offerte'
      path: '/offerte'
      fullPath: '/offerte'
      preLoaderRoute: typeof AppOfferteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/piu-venduti': {
      id: '/_app/piu-venduti'
      path: '/piu-venduti'
      fullPath: '/piu-venduti'
      preLoaderRoute: typeof AppPiuVendutiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/preferiti': {
      id: '/_app/preferiti'
      path: '/preferiti'
      fullPath: '/preferiti'
      preLoaderRoute: typeof AppPreferitiRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorie': {
      id: '/admin/categorie'
      path: '/categorie'
      fullPath: '/admin/categorie'
      preLoaderRoute: typeof AdminCategorieRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clienti': {
      id: '/admin/clienti'
      path: '/clienti'
      fullPath: '/admin/clienti'
      preLoaderRoute: typeof AdminClientiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/impostazioni': {
      id: '/admin/impostazioni'
      path: '/impostazioni'
      fullPath: '/admin/impostazioni'
      preLoaderRoute: typeof AdminImpostazioniRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ordini': {
      id: '/admin/ordini'
      path: '/ordini'
      fullPath: '/admin/ordini'
      preLoaderRoute: typeof AdminOrdiniRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/prodotti': {
      id: '/admin/prodotti'
      path: '/prodotti'
      fullPath: '/admin/prodotti'
      preLoaderRoute: typeof AdminProdottiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sottocategorie': {
      id: '/admin/sottocategorie'
      path: '/sottocategorie'
      fullPath: '/admin/sottocategorie'
      preLoaderRoute: typeof AdminSottocategorieRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/utenti': {
      id: '/admin/utenti'
      path: '/utenti'
      fullPath: '/admin/utenti'
      preLoaderRoute: typeof AdminUtentiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/categorie/$slug': {
      id: '/_app/categorie/$slug'
      path: '/$slug'
      fullPath: '/categorie/$slug'
      preLoaderRoute: typeof AppCategorieSlugRouteImport
      parentRoute: typeof AppCategorieRoute
    }
    '/_app/prodotto/$id': {
      id: '/_app/prodotto/$id'
      path: '/prodotto/$id'
      fullPath: '/prodotto/$id'
      preLoaderRoute: typeof AppProdottoIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppCategorieRouteChildren {
  AppCategorieSlugRoute: typeof AppCategorieSlugRoute
}

const AppCategorieRouteChildren: AppCategorieRouteChildren = {
  AppCategorieSlugRoute: AppCategorieSlugRoute,
}

const AppCategorieRouteWithChildren = AppCategorieRoute._addFileChildren(
  AppCategorieRouteChildren,
)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppCataloghiRoute: typeof AppCataloghiRoute
  AppCategorieRoute: typeof AppCategorieRouteWithChildren
  AppCercaRoute: typeof AppCercaRoute
  AppChiSiamoRoute: typeof AppChiSiamoRoute
  AppConfrontaRoute: typeof AppConfrontaRoute
  AppConsegneRoute: typeof AppConsegneRoute
  AppContattiRoute: typeof AppContattiRoute
  AppDoveSiamoRoute: typeof AppDoveSiamoRoute
  AppHomeRoute: typeof AppHomeRoute
  AppIMieiOrdiniRoute: typeof AppIMieiOrdiniRoute
  AppNovitaRoute: typeof AppNovitaRoute
  AppOfferteRoute: typeof AppOfferteRoute
  AppPiuVendutiRoute: typeof AppPiuVendutiRoute
  AppPreferitiRoute: typeof AppPreferitiRoute
  AppProdottoIdRoute: typeof AppProdottoIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppCataloghiRoute: AppCataloghiRoute,
  AppCategorieRoute: AppCategorieRouteWithChildren,
  AppCercaRoute: AppCercaRoute,
  AppChiSiamoRoute: AppChiSiamoRoute,
  AppConfrontaRoute: AppConfrontaRoute,
  AppConsegneRoute: AppConsegneRoute,
  AppContattiRoute: AppContattiRoute,
  AppDoveSiamoRoute: AppDoveSiamoRoute,
  AppHomeRoute: AppHomeRoute,
  AppIMieiOrdiniRoute: AppIMieiOrdiniRoute,
  AppNovitaRoute: AppNovitaRoute,
  AppOfferteRoute: AppOfferteRoute,
  AppPiuVendutiRoute: AppPiuVendutiRoute,
  AppPreferitiRoute: AppPreferitiRoute,
  AppProdottoIdRoute: AppProdottoIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminCategorieRoute: typeof AdminCategorieRoute
  AdminClientiRoute: typeof AdminClientiRoute
  AdminImpostazioniRoute: typeof AdminImpostazioniRoute
  AdminOrdiniRoute: typeof AdminOrdiniRoute
  AdminProdottiRoute: typeof AdminProdottiRoute
  AdminSottocategorieRoute: typeof AdminSottocategorieRoute
  AdminUtentiRoute: typeof AdminUtentiRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategorieRoute: AdminCategorieRoute,
  AdminClientiRoute: AdminClientiRoute,
  AdminImpostazioniRoute: AdminImpostazioniRoute,
  AdminOrdiniRoute: AdminOrdiniRoute,
  AdminProdottiRoute: AdminProdottiRoute,
  AdminSottocategorieRoute: AdminSottocategorieRoute,
  AdminUtentiRoute: AdminUtentiRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
